#!/bin/bash
# Quick start script untuk Blackbox Farm dengan Cloudflare Workers

cd /home/gaco/projects/blackbox-farm

echo "🚀 Starting Blackbox Farm with Cloudflare Workers Temp Email"
echo ""
echo "Available domains in your Cloudflare Workers:"
echo "- Check your cloudflare_temp_email worker configuration"
echo ""
echo "Default settings:"
echo "  Provider: cloudflare"
echo "  API: \${CF_API_URL:-set it in .env}"
echo "  Domain: (will be auto-generated by API)"
echo ""
echo "Press ENTER to launch..."
read

.venv/bin/python main.py
